config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => 'admin/sidekiq'
    namespace :internal do
      resources :linkedin_schedulers
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'public/articles#index'

  get 'about', to: 'public/about_me#index'
  get 'contact', to: 'public/contacts#index'
  post 'subscriptions', to: 'public/subscribe_article#create'
  
  scope module: 'code_reminder' do
    resources :code_reminders, only: [:new, :create, :edit, :update, :destroy]
  end

  scope module: 'public' do
    get 'projects', to: 'projects#index'
    resources :experiences, only: %i[show index]
    resources :articles, only: %i[show index] do
      resources :comments, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :experiences, only: %i[show index], defaults: { format: 'json' }
      resources :quehoraes, only: %i[index], defaults: { format: 'json' }
    end
  end

namespace :real_time_geo_system do
  get '/', to: 'real_time_geo_system#index'
  get '/:id', to: 'real_time_geo_system#show'
  get '/querier_panel/:id', to: 'real_time_geo_system#querier_panel'
end

  get 'chat-room', to: 'chat_room/rooms#show'

  mount ActionCable.server => '/cable'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible

  has_rich_text :content
  has_many :comments, dependent: :destroy
  has_many :internal_linkedin_schedulers, dependent: :destroy, class_name: 'Internal::LinkedinScheduler'
  validates :title, presence: true
  validates :content, presence: true
  after_save :notify_subscribers

  private

  def notify_subscribers
    NotifySubscribersJob.perform_later self if status == 'public-notify'
  end
end

app/models/code_reminder.rb
# frozen_string_literal: true

class CodeReminder < ApplicationRecord
  enum cadence_unit: { weeks: 0, days: 1, months: 2 }
  validates :email, uniqueness: true, presence: true
  validates :cadence, presence: true
  validates :cadence_unit, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public public-notify private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/experience.rb
# frozen_string_literal: true

class Experience < ApplicationRecord
end

app/models/internal.rb
# frozen_string_literal: true

module Internal
  def self.table_name_prefix
    'internal_'
  end
end

app/models/internal/linkedin_scheduler.rb
# frozen_string_literal: true

module Internal
  class LinkedinScheduler < ApplicationRecord
    belongs_to :article
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
end

app/models/personal_project.rb
# frozen_string_literal: true

class PersonalProject < ApplicationRecord
end

app/models/route_hit.rb
class RouteHit < ApplicationRecord
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  validates :email, uniqueness: true, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/internal/linkedin_schedulers_controller.rb
# frozen_string_literal: true

module Internal
  class LinkedinSchedulersController < InheritedResources::Base
    def index
      @internal_linkedin_schedulers = LinkedinScheduler.all.order(schedule_for: :desc)
    end

    def new
      @internal_linkedin_scheduler = LinkedinScheduler.new
    end

    def create
      create_and_enqueue_post(linkedin_scheduler_params)
      redirect_to internal_linkedin_schedulers_path
    end

    def show
      @internal_linkedin_scheduler = LinkedinScheduler.find(params[:id])
    end

    def edit
      @internal_linkedin_scheduler = LinkedinScheduler.find(params[:id])
      redirect_if_already_sent(@internal_linkedin_scheduler)
    end

    def update
      redirect_or_delete(params[:id])
      create_and_enqueue_post(linkedin_scheduler_params)
      redirect_to internal_linkedin_schedulers_path
    end

    def destroy
      redirect_or_delete(params[:id])
      redirect_to internal_linkedin_schedulers_path
    end

    private

    def redirect_or_delete(id)
      redirect_if_already_sent(LinkedinScheduler.find(id))
      LinkedinScheduler.destroy(id)
    end

    def redirect_if_already_sent(schedule)
      redirect_to internal_linkedin_schedulers_path if schedule.sent
    end

    def create_and_enqueue_post(linkedin_scheduler_params)
      linkedin_schedule = LinkedinScheduler.create!(linkedin_scheduler_params)
      schedule_for_utc = linkedin_schedule.schedule_for.utc
      SchedulePostJob.set(wait_until: schedule_for_utc).perform_later(linkedin_schedule.id)
    end

    def linkedin_scheduler_params
      params.require(:internal_linkedin_scheduler).permit(:article_id, :post_body, :schedule_for)
    end
  end
end

app/helpers/about_me_helper.rb
# frozen_string_literal: true

module AboutMeHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/experiences_helper.rb
# frozen_string_literal: true

module ExperiencesHelper
end

app/helpers/internal/linkedin_schedulers_helper.rb
# frozen_string_literal: true

module Internal
  module LinkedinSchedulersHelper
  end
end

app/helpers/subscribe_article_helper.rb
# frozen_string_literal: true

module SubscribeArticleHelper
end

app/views/internal/linkedin_schedulers/_form.html.erb
<%= form_with(model: internal_linkedin_scheduler) do |form| %>
  <% if internal_linkedin_scheduler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internal_linkedin_scheduler.errors.count, "error") %> prohibited this internal_linkedin_scheduler from being saved:</h2>

      <ul>
        <% internal_linkedin_scheduler.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :article_id, :required => true %>
    <%= form.number_field :article_id, :required => true %>
  </div>

  <div>
    <%= form.label :post_body, :required => true %>
    <%= form.text_area :post_body, :required => true %>
  </div>

  <div>
    <%= form.label :schedule_for, :required => true %>
    <%= form.datetime_select :schedule_for, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/internal/linkedin_schedulers/edit.html.erb
<h1>Editing Internal Linkedin Scheduler</h1>

<%= render 'form', internal_linkedin_scheduler: @internal_linkedin_scheduler %>

<%= link_to 'Show', @internal_linkedin_scheduler %> |
<%= link_to 'Back', internal_linkedin_schedulers_path %>

app/views/internal/linkedin_schedulers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Internal Linkedin Schedulers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @internal_linkedin_schedulers.each do |internal_linkedin_scheduler| %>
      <tr>
        <td><%= link_to 'Show', internal_linkedin_scheduler %> <%= internal_linkedin_scheduler.article.title %></td>
        <% unless internal_linkedin_scheduler.sent %>
          <td><%= link_to 'Edit', edit_internal_linkedin_scheduler_path(internal_linkedin_scheduler) %></td>
          <td><%= link_to 'Destroy', internal_linkedin_scheduler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td>Sent: <%= internal_linkedin_scheduler.sent %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Internal Linkedin Scheduler', new_internal_linkedin_scheduler_path %>

app/views/internal/linkedin_schedulers/new.html.erb
<h1>New Internal Linkedin Scheduler</h1>

<%= render 'form', internal_linkedin_scheduler: @internal_linkedin_scheduler %>

<%= link_to 'Back', internal_linkedin_schedulers_path %>

app/views/internal/linkedin_schedulers/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= @internal_linkedin_scheduler.article.title %>
</div>

<div>
  <%= @internal_linkedin_scheduler.schedule_for %>
</div>

<div>
  <%= @internal_linkedin_scheduler.post_body %>
</div>

<%= link_to 'Edit', edit_internal_linkedin_scheduler_path(@internal_linkedin_scheduler) %> |
<%= link_to 'Back', internal_linkedin_schedulers_path %>