config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => 'admin/sidekiq'
    namespace :internal do
      resources :linkedin_schedulers
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'public/articles#index'

  get 'about', to: 'public/about_me#index'
  get 'contact', to: 'public/contacts#index'
  post 'subscriptions', to: 'public/subscribe_article#create'
  
  scope module: 'code_reminder' do
    resources :code_reminders, only: [:new, :create, :edit, :update, :destroy]
  end

  scope module: 'public' do
    get 'projects', to: 'projects#index'
    resources :experiences, only: %i[show index]
    resources :articles, only: %i[show index] do
      resources :comments, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :experiences, only: %i[show index], defaults: { format: 'json' }
      resources :quehoraes, only: %i[index], defaults: { format: 'json' }
    end
  end

namespace :real_time_geo_system do
  get '/', to: 'real_time_geo_system#index'
  get '/:id', to: 'real_time_geo_system#show'
  get '/querier_panel/:id', to: 'real_time_geo_system#querier_panel'
end

  get 'chat-room', to: 'chat_room/rooms#show'

  mount ActionCable.server => '/cable'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible

  has_rich_text :content
  has_many :comments, dependent: :destroy
  has_many :internal_linkedin_schedulers, dependent: :destroy, class_name: 'Internal::LinkedinScheduler'
  validates :title, presence: true
  validates :content, presence: true
  after_save :notify_subscribers

  private

  def notify_subscribers
    NotifySubscribersJob.perform_later self if status == 'public-notify'
  end
end

app/models/code_reminder.rb
# frozen_string_literal: true

class CodeReminder < ApplicationRecord
  enum cadence_unit: { weeks: 0, days: 1, months: 2 }
  validates :email, uniqueness: true, presence: true
  validates :cadence, presence: true
  validates :cadence_unit, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/experience.rb
# frozen_string_literal: true

class Experience < ApplicationRecord
end

app/models/internal.rb
# frozen_string_literal: true

module Internal
  def self.table_name_prefix
    'internal_'
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
end

app/models/personal_project.rb
# frozen_string_literal: true

class PersonalProject < ApplicationRecord
end

app/models/route_hit.rb
class RouteHit < ApplicationRecord
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  validates :email, uniqueness: true, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/about_me_helper.rb
# frozen_string_literal: true

module AboutMeHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/experiences_helper.rb
# frozen_string_literal: true

module ExperiencesHelper
end

app/helpers/subscribe_article_helper.rb
# frozen_string_literal: true

module SubscribeArticleHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-pad">
  <a class="navbar-brand text-decoration-none" href="<%= about_path %>" >Hamdaan Khalid</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= about_path %>">About Me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= experiences_path %>">Resume</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= articles_path %>">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= projects_url %>">Personal Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= chat_room_path %>">Live Chat Room</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= real_time_geo_system_path %>">Real Time Geo-Spatial Query</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-decoration-none" href="<%= contact_path %>">Contact Me</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hamdaan Khalid | <%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>" id=<%= message_type%>><%= message %></div>
      <% end %>
    <div style="padding-top: 25px; margin: 0px 20px">
        <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>